<a href="https://colab.research.google.com/github/imabhinav-singh/CS360/blob/master/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Part 1

Question 1: Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [ ]:
import numpy as np
arr = np.hstack((np.hstack((np.zeros((5,)), np.full((5,), 1, dtype=int))), np.full((5,), 5, dtype=int)))
print(arr)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 5. 5. 5. 5. 5.]


Question 2: Write a NumPy program to create an array of all the even integers from 10 to 50.

In [ ]:
import numpy as np
arr = np.arange(10, 52, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Question 3: Write a NumPy program to generate a random number between 0 and
1.

In [ ]:
import numpy as np

def randArray():
  return np.random.rand(3, 3)

def main():
  print(randArray())

if __name__ == "__main__":
  main()  

[[0.65383799 0.76900618 0.57395681]
 [0.61613176 0.28464081 0.57742906]
 [0.68760667 0.33138829 0.75092747]]


Question 4: Write a NumPy program to save the matrix (generated in question 3) to a text file and load it.

In [ ]:
def main():
  filename = open("matrix.txt", "w")
  filename.write(str(randArray()))
  filename.close()

if __name__ == "__main__":
  main()

#Part 2

Question 1: Write a python program to read an image and save the image as a matrix to a .csv file using pandas.

In [23]:
from PIL import Image
import pandas as pd
import numpy as np

img = Image.open('new_pic.jpeg')
imgArr = np.array(img) 
pd.DataFrame(imgArr.reshape(imgArr.shape[0]*imgArr.shape[1], imgArr.shape[2])).to_csv('image_matrix.csv')

Question 2: Write a program to import excel data from the .csv file
(generated in question 1) by excluding the last row and last
column.

In [26]:
import pandas as pd
csv_reader = pd.read_csv('image_matrix.csv', index_col=0, usecols=[1,2], skiprows=-1)
print(csv_reader)

      1
0      
63  175
63  175
63  175
63  176
63  176
..  ...
2   106
2   107
2   107
1   106
1   106

[167000 rows x 1 columns]


Question 3: Write a Pandas program to create the today's date.

In [28]:
import pandas as pd
from datetime import date
date_ = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(date_)

Today's date:
2020-08-22 00:00:00


#Part 3

Question 1: Create a mini calculator to know the age of a person after
putting the range (i.e. date of birth and current date).

In [40]:
from datetime import datetime
dob = input('Enter date of birth: ')
try:
  dob = datetime.strptime(dob, '%Y, %m, %d')
except ValueError:
  print("Incorrect format. (use 2020, 08, 30)")
currd = input('Enter current date: ')
try:
  currd = datetime.strptime(currd, '%Y, %m, %d')
except ValueError:
  print("Incorrect format. (use 2020, 08, 30)")
diff = (currd - dob).total_seconds()
year = int(diff / 31536000)
diff %= 31536000
months = int(diff / 2592000)
diff %= 2592000
days = int(diff / 86400)
print(str(year)+" years, "+str(months)+" months, and "+str(days)+" days old.")

Enter date of birth: 2000, 10, 18
Enter current date: 2020, 08, 22
19 years, 10 months, and 13 days old.
