<a href="https://colab.research.google.com/github/imabhinav-singh/CS360/blob/master/Assignment0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1:- 
#Write a python program to get the Python version you are using

In [ ]:
import platform
print(platform.python_version())

3.6.9


Question 2:- 
#Write a Python program to locate Python site-packages

In [ ]:
import site
site.getsitepackages()

['/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.6/dist-packages']

Question 3:-
#Write a python program to get the path and name of the file that is currently executing

In [3]:
import inspect, os
print(inspect.getfile(inspect.currentframe()))
print(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))

<ipython-input-3-999536cf70d4>
/content


Question 4:- 
#Write a python program to randomly generate two matrices of size [2x3 and 3x2] and do the matrix multiplication using the two generated matrices. (Say A = BC)

In [8]:
import numpy

def randomMatrixMult():
  #create matrices with random values
  arr_A = numpy.random.randint(1, 50, size=(2, 3))
  arr_B = numpy.random.randint(1, 50, size=(3, 2))

  #multiplication of matrices
  return numpy.dot(arr_A, arr_B)

def main():
  print(randomMatrixMult())

if __name__ == "__main__":
  main()

[[ 662 1380]
 [ 394  870]]


Question 5:-
#Use a for loop to implement the above question five times and thereafter take the average of all the five matrices and display the result.

In [10]:
def averageMatrix():
  arr_C = randomMatrixMult()
  for i in range(2, 5):
    arr_C += randomMatrixMult()
  
  return arr_C/5

def main():
  print(averageMatrix())

if __name__ == "__main__":
  main()

[[1449.6 1725.6]
 [1490.8 1733. ]]


Question 6:-
#Write a program to transfer the matrix (generated in question 5) to the csv file and then read the same matrix and display the transposition of it.

In [12]:
import csv
def transposeMatrix(M):
  numpy.savetxt("Matrix.csv", M, delimiter=",")

  A = numpy.array(list(csv.reader(open("Matrix.csv", "rt"), delimiter=","))).astype("float")
  return A.transpose()

def main():
  M = averageMatrix()
  print("Original Matrix:")
  print(M)
  print("\nTranspose Matrix:")
  print(transposeMatrix(M))

if __name__ == "__main__":
  main()

Original Matrix:
[[1601.  1784.2]
 [1893.2 2020.8]]

Transpose Matrix:
[[1601.  1893.2]
 [1784.2 2020.8]]


Question 7:-
#Write a program to find the mean, mode, and median of the above-mentioned matrix.

In [23]:
from scipy import stats

A = transposeMatrix(averageMatrix())
print("Matrix is: \n", A)

#calculate mean
print("Mean is: ", numpy.mean(A))

#calculate median
print("Median is: ", numpy.median(A))

#calculate mode
print("Mode is: ", stats.mode(A.reshape(1,4))[0])

Matrix is: 
 [[ 940.2 1433.2]
 [1703.2 2641.2]]
Mean is:  1679.45
Median is:  1568.2
Mode is:  [[ 940.2 1433.2 1703.2 2641.2]]


Question 8:-
#Write a program to print the upper triangle of the matrix

In [24]:
A = transposeMatrix(averageMatrix())
print("Matrix is: \n", A)

#calculate upper triangular matrix
print("Upper triangular matrix is: \n", numpy.triu(A)) 

Matrix is: 
 [[1557.6 1510.6]
 [1598.2 1402.8]]
Upper triangular matrix is: 
 [[1557.6 1510.6]
 [   0.  1402.8]]


Question 9:-
#Write a Python program to read specific columns of a given CSV file and print the content of the columns. (Column number should be given by the user)

In [27]:
import csv

def displayColumn(filename, columnNumber):
  with open(filename) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=",")
    for row in  csv_reader:
      print(row[columnNumber])

def main():
  filename = input("Enter filename:- ")
  cNo = input("Enter column number:- ")
  displayColumn(filename, int(cNo))

if __name__ == "__main__":
  main()

Enter filename:- Matrix.csv
Enter column number:- 1
1.598200000000000045e+03
1.402799999999999955e+03


Question 10:-
#Write a Python program to replace a user-defined number present in the CSV file by the character ‘A’.

In [29]:
def replaceChar(filename, pChar, nChar):
  text = open(filename, "r")
  text = ''.join([i for i in text]).replace(nChar, pChar)
  x = open(filename,"w")
  x.writelines(text)
  x.close()

def main():
  filename = input("Enter filename:- ")
  pChar = input("Enter character to be replaced:- ")
  replaceChar(filename, pChar, "A")

if __name__ == "__main__":
  main()

Enter filename:- Matrix.csv
Enter character to be replaced:- 1
